services:
  postgres:
    image: postgres:14
    container_name: klasseserver_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - klasseserver_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: klasseserver_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - klasseserver_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: klasseserver_mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - klasseserver_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: klasseserver_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/www:/usr/share/nginx/html:ro
      - ./nginx/php:/var/www/php  # Changed from /var/www/html to /var/www/php
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - klasseserver_network
    depends_on:
      - pgadmin
      - mosquitto
      - postgres

networks:
  klasseserver_network:
    driver: bridge

volumes:
  pgadmin-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/volumes/pgadmin-data
