version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: klasseserver_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - klasseserver_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: klasseserver_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - klasseserver_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: klasseserver_mqtt
    ports:
      - "1883:1883"  # MQTT default port
      - "9001:9001"  # Websockets port
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - klasseserver_network

  nginx:
    build: ./nginx
    container_name: klasseserver_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/certbot
    networks:
      - klasseserver_network
    depends_on:
      - pgadmin
      - mosquitto

networks:
  klasseserver_network:
    driver: bridge